### ISSUE TITLE
Stratasys Fortus 250, use Fox, Prodigy or Quantum instead?

### ISSUE THREAD

**Issue by rowlandski** [bvanheu/stratasys#16]
Hi,

will your code work on Fortus 250 machine cartridges?

And which version of Raspberry Pi did you use, or doesn't if matter? 

Many thanks.

Regards,

Rowland

**Comment by bvanheu** [comment]
It should work with a Fortus 250.

I used a Raspberry Pi 1, but I'm not sure regarding the RP2. The code will work, but the 1wire might be on another pin.

**Comment by rowlandski** [comment]
Thanks for your reply.

I will be using/editing a Fortus cartridge.

What should i use for machine "type"?

Print information about a cartridge

You have to provide the machine type (fox, prodigy or quantum) and the EEPROM uid, in hexadecimal form without the '0x' prefix. Note that the EEPROM uid use to end with "23".

$ ./stratasys-cli.py eeprom -t fox -e 4343434343434343 -i random_file.bin

Many thanks.

**Comment by rowlandski** [comment]
Prodigy works for Fortus (250).
