### ISSUE TITLE
Can Dimention or Fortus printers be used?

### ISSUE THREAD

**Issue by strozster** [bvanheu/stratasys#23]
Can Dimention or Fortus printers be used? I have the .bin file that I copied from the device. Is it possible to view the contents of it like other printers? Right now I am getting errors running the stratasys-cli.py eeprom -t command.

**Comment by bvanheu** [comment]
Yes you should be able to use this software to parse Dimension & Fortus printer cartridge.

Please tell me the exact line you're using to parse the `.bin` file that gives you an error, or I cannot help you.

You should use something similar to:
```
$ ./stratasys-cli.py eeprom -t fox -e 4343434343434343 -i random_file.bin
````

Make sure to replace `fox` by the correct machine type, `4343434343434343` by the EEPROM id and `random_file.bin` by your filename.

**Comment by strozster** [comment]
Attached is a screen with 3 commands I ran on a eeprom.bin file that I retrieved. It seems I get an error with "dimension" as there is no option for it. When I tried the same thing replacing the machine with fox it gave several errors. 

![eeprom read attempt](https://cloud.githubusercontent.com/assets/5598850/9008007/e8c478de-3764-11e5-89df-864bdedd661c.JPG)

**Comment by bvanheu** [comment]
Try with each of them until you have a correct decryption.

Also, make sure the EEPROM UID ends with `23`. Yours seem to start with 23. You should reverse it.

**Comment by strozster** [comment]
for example if my eeprom uid reads 23a29e1g10222272 what should I be typing in? a29e1g1022227223? or 27222201g1e92a32?

**Comment by bvanheu** [comment]
`23 a2 9e 1g 10 22 22 72`
should be:
`72 22 22 10 1g 9e a2 23`

(without any spaces of course).

there should not be any `g` in there though, make sure you're using a valid EEPROM id.

**Comment by strozster** [comment]
Below are screens of the output for a script I wrote to go through all of the options. Errors were present for all. There is no g I flipped a few characters. If you need anything else let me know.

Thanks for all the help. 
![ex1](https://cloud.githubusercontent.com/assets/5598850/9010574/a7cc811c-3775-11e5-9824-c36ddaadd46b.JPG)
![ex2](https://cloud.githubusercontent.com/assets/5598850/9010575/a7cd083a-3775-11e5-826b-4bbdba7b17a2.JPG)

**Comment by bvanheu** [comment]
The wrong checksum means the decryption was not successful, probably because the wrong key is used.

People in the past have successfully decrypted EEPROM for Dimension printers, so make sure the EEPROM dump is correct and you're using the right EEPROM uid.

If you're *pretty confident* you did everything right, you can send me your EEPROM + the EEPROM uid by email (see in the README) and i'll see what I can do. You might have an exotic printer model ;)

**Comment by toma678** [comment]
Any update on this? The EEPROM dump I have is throwing checksum errors on every machine type listed. I can send you the dump and ID if possible. I'm running a Stratasys Dimension SST 768.

**Comment by RobListon** [comment]
I am currently using this project with both my Dimension and Fortus machines. It works great.

**Comment by 573F4N077** [comment]
@RobListon 
what is the model name you are using? (prodigy or fox or...) thx

**Comment by RobListon** [comment]
I am using the prodigy type for both the Dimension and Fortus.

**Comment by strozster** [comment]
@bvanheu I know your comment is over a year old, am I still able to send you an email with the eeprom dump for the printer I am trying to use? I have it working for the Dimension but not the Fortus (I'll specify the model in the e-mail), I continue to get the checksum error. Thanks.

**Comment by bvanheu** [comment]
sure.

**Comment by strozster** [comment]
Sent you an email, let me know if you get it! Thanks

**Comment by LUKIBOB** [comment]
I have the eeprom from a ABS-M30 canister that goes in Fortus360, 400,... Will this code work for it?
![dsc02663](https://cloud.githubusercontent.com/assets/8014082/19354152/c502f630-9133-11e6-9a99-af765bdb4441.JPG)

**Comment by HaveBlueXST** [comment]
LUKIBOB, yes, the code will work with it (there's no MAC authentication to deal with, unlike later chips).

**Comment by LUKIBOB** [comment]
Thanks HaveBlueXST, I just got a Titan TI and have near limitless supplies of canisters. Need to refill them and hopefully find a material setting with the correct temperatures. Wish I could set the temp and print speed manually like Repetier Host. I'll be working on that next
