### ISSUE TITLE
Question: Key Fragment

### ISSUE THREAD

**Issue by hahathejellyfox** [bvanheu/stratasys#26]
Hello, first of all I would like to say thank you for your wonderful software. I am planning to use it soon and was wondering what I should enter for the key fragment argument when creating a new EEPROM file.

Cheers,
Danny

**Comment by bvanheu** [comment]
Hi,

You can put whatever you want for the key fragment. The format is 8 bytes,
hex encoded.

e.g.:
0123456789abcdef
4242434445464748

The key fragment is used to build the key that will be used to both encrypt
and decrypt the EEPROM.

Benjamin Vanheuverzwijn
Le 2015-12-04 4:38 PM, "hahathejellyfox" <notifications@github.com> a
écrit :

**Comment by hahathejellyfox** [comment]
Thanks :) I was also wondering what the initial material and current material fields are for

**Comment by bvanheu** [comment]
`initial material quantity`: the quantity of material in cubic inches initially in the cartridge
`current material quantity`: the remaining quantity of material in cubic inches.

When `initial material quantity` == `current material quantity`, it means that the cartridge is full (100%).

**Comment by hahathejellyfox** [comment]
Excellent thanks for all the help
